using MainAPp;
Laptop laptop = new Laptop();
laptop.Ram = 8;
laptop.Storage = 512;
laptop.Keyboard = "New";
System.Console.WriteLine(laptop.WeightCheck(10));
laptop.AddRam(16);
laptop.AddStorage(1024);
laptop.Print();
Smartphone smarthphone = new Smartphone();
smarthphone.Ram = 4;
smarthphone.Storage = 128;
smarthphone.Keyboard = "wasd";
smarthphone.AddRam(4);
smarthphone.AddStorage(124);
smarthphone.Print();
smarthphone.TakeSelfies();
smarthphone.TakeSelfies();
smarthphone.TakeSelfies();
smarthphone.TakeSelfies();
Compute computer = new Compute();
